from PyQt5 import QtCore, QtWidgets

class ArdupilotBoxWidget(QtWidgets.QWidget):
     def __init__(self, page, parent=None):
            QtWidgets.QWidget.__init__(self, parent=parent)
            
            self.groupBoxArdu = QtWidgets.QGroupBox(page)
            self.groupBoxArdu.setGeometry(QtCore.QRect(530, 0, 451, 501))
            self.groupBoxArdu.setAutoFillBackground(False)
            self.groupBoxArdu.setStyleSheet("border:0")
            self.groupBoxArdu.setTitle("")
            self.groupBoxArdu.setObjectName("groupBoxArdu")
            self.groupBoxArdu.lower()

            self.flightmodeSetArduKey = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.flightmodeSetArduKey.setGeometry(QtCore.QRect(260, 270, 31, 31))
            self.flightmodeSetArduKey.setText("")
            self.flightmodeSetArduKey.setMaxLength(1)
            self.flightmodeSetArduKey.setObjectName("flightmodeSetArduKey")
            self.armSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.armSetArduLabel.setGeometry(QtCore.QRect(210, 230, 31, 21))
            self.armSetArduLabel.setObjectName("armSetArduLabel")
            self.beeperSetArduKey = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.beeperSetArduKey.setGeometry(QtCore.QRect(260, 320, 31, 31))
            self.beeperSetArduKey.setText("")
            self.beeperSetArduKey.setMaxLength(1)
            self.beeperSetArduKey.setObjectName("beeperSetArduKey")
            self.beeperSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.beeperSetArduLabel.setGeometry(QtCore.QRect(200, 330, 51, 21))
            self.beeperSetArduLabel.setObjectName("beeperSetArduLabel")
            # self.angleSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            # self.angleSetArduLabel.setGeometry(QtCore.QRect(90, 280, 41, 21))
            # self.angleSetArduLabel.setObjectName("angleSetArduLabel")
            self.currentSetArduMode = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.currentSetArduMode.setGeometry(QtCore.QRect(310, 270, 31, 31))
            self.currentSetArduMode.setText("")
            self.currentSetArduMode.setMaxLength(1)
            self.currentSetArduMode.setObjectName("currentSetArduMode")
            self.modesSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.modesSetArduLabel.setGeometry(QtCore.QRect(210, 100, 121, 21))
            self.modesSetArduLabel.setObjectName("modesSetArduLabel")
            self.armSetArduKey = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.armSetArduKey.setGeometry(QtCore.QRect(260, 220, 31, 31))
            self.armSetArduKey.setText("")
            self.armSetArduKey.setMaxLength(1)
            self.armSetArduKey.setObjectName("armSetArduKey")
            self.prearmSetArduKey = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.prearmSetArduKey.setGeometry(QtCore.QRect(260, 170, 31, 31))
            self.prearmSetArduKey.setText("")
            self.prearmSetArduKey.setMaxLength(1)
            self.prearmSetArduKey.setObjectName("prearmSetArduKey")
            self.flightModeSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.flightModeSetArduLabel.setGeometry(QtCore.QRect(170, 280, 100, 21))
            self.flightModeSetArduLabel.setObjectName("flightModeSetArduLabel")
            # self.acroSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            # self.acroSetArduLabel.setGeometry(QtCore.QRect(220, 280, 31, 21))
            # self.acroSetArduLabel.setObjectName("acroSetArduLabel")
            self.OSDSetArduKey = QtWidgets.QLineEdit(self.groupBoxArdu)
            self.OSDSetArduKey.setGeometry(QtCore.QRect(260, 370, 31, 31))
            self.OSDSetArduKey.setText("")
            self.OSDSetArduKey.setMaxLength(1)
            self.OSDSetArduKey.setObjectName("OSDSetArduKey")
            self.prearmSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.prearmSetArduLabel.setGeometry(QtCore.QRect(200, 180, 51, 21))
            self.prearmSetArduLabel.setObjectName("prearmSetArduLabel")
            self.OSDDisableSetArduLabel = QtWidgets.QLabel(self.groupBoxArdu)
            self.OSDDisableSetArduLabel.setGeometry(QtCore.QRect(140, 380, 111, 21))
            self.OSDDisableSetArduLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
            self.OSDDisableSetArduLabel.setObjectName("OSDDisableSetArduLabel")



            _translate = QtCore.QCoreApplication.translate
            self.armSetArduLabel.setText(_translate("MainWindow", "Arm"))
            self.beeperSetArduLabel.setText(_translate("MainWindow", "Beeper"))
            #self.angleSetArduLabel.setText(_translate("MainWindow", "Angle"))
            self.modesSetArduLabel.setText(_translate("MainWindow", "Modes/Features"))
            self.flightModeSetArduLabel.setText(_translate("MainWindow", "Flight Mode"))
            #self.acroSetArduLabel.setText(_translate("MainWindow", "Acro"))
            self.prearmSetArduLabel.setText(_translate("MainWindow", "Prearm"))
            self.OSDDisableSetArduLabel.setText(_translate("MainWindow", "OSD Disable SW"))
    