from PyQt5 import QtCore, QtWidgets

class BetaFlightBoxWidget(QtWidgets.QWidget):
    def __init__(self, page, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)

        self.groupBoxBeta = QtWidgets.QGroupBox(page)
        self.groupBoxBeta.setGeometry(QtCore.QRect(530, 0, 451, 501))
        self.groupBoxBeta.setAutoFillBackground(False)
        self.groupBoxBeta.setStyleSheet("border:0")
        self.groupBoxBeta.setTitle("")
        self.groupBoxBeta.setObjectName("groupBoxBeta")
        self.groupBoxBeta.lower()

        self.flightmodeSetBetaKey = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.flightmodeSetBetaKey.setGeometry(QtCore.QRect(260, 270, 31, 31))
        self.flightmodeSetBetaKey.setText("")
        self.flightmodeSetBetaKey.setMaxLength(1)
        self.flightmodeSetBetaKey.setObjectName("flightmodeSetBetaKey")
        self.armSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.armSetBetaLabel.setGeometry(QtCore.QRect(210, 230, 31, 21))
        self.armSetBetaLabel.setObjectName("armSetBetaLabel")
        self.beeperSetBetaKey = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.beeperSetBetaKey.setGeometry(QtCore.QRect(260, 320, 31, 31))
        self.beeperSetBetaKey.setText("")
        self.beeperSetBetaKey.setMaxLength(1)
        self.beeperSetBetaKey.setObjectName("beeperSetBetaKey")
        self.beeperSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.beeperSetBetaLabel.setGeometry(QtCore.QRect(200, 330, 51, 21))
        self.beeperSetBetaLabel.setObjectName("beeperSetBetaLabel")
        self.angleSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.angleSetBetaLabel.setGeometry(QtCore.QRect(90, 280, 41, 21))
        self.angleSetBetaLabel.setObjectName("angleSetBetaLabel")
        self.currentSetBetaMode = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.currentSetBetaMode.setGeometry(QtCore.QRect(310, 270, 31, 31))
        self.currentSetBetaMode.setText("")
        self.currentSetBetaMode.setMaxLength(1)
        self.currentSetBetaMode.setObjectName("currentSetBetaMode")
        self.modesSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.modesSetBetaLabel.setGeometry(QtCore.QRect(210, 100, 121, 21))
        self.modesSetBetaLabel.setObjectName("modesSetBetaLabel")
        self.armSetBetaKey = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.armSetBetaKey.setGeometry(QtCore.QRect(260, 220, 31, 31))
        self.armSetBetaKey.setText("")
        self.armSetBetaKey.setMaxLength(1)
        self.armSetBetaKey.setObjectName("armSetBetaKey")
        self.prearmSetBetaKey = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.prearmSetBetaKey.setGeometry(QtCore.QRect(260, 170, 31, 31))
        self.prearmSetBetaKey.setText("")
        self.prearmSetBetaKey.setMaxLength(1)
        self.prearmSetBetaKey.setObjectName("prearmSetBetaKey")
        self.horizonSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.horizonSetBetaLabel.setGeometry(QtCore.QRect(150, 280, 61, 21))
        self.horizonSetBetaLabel.setObjectName("horizonSetBetaLabel")
        self.acroSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.acroSetBetaLabel.setGeometry(QtCore.QRect(220, 280, 31, 21))
        self.acroSetBetaLabel.setObjectName("acroSetBetaLabel")
        self.OSDSetBetaKey = QtWidgets.QLineEdit(self.groupBoxBeta)
        self.OSDSetBetaKey.setGeometry(QtCore.QRect(260, 370, 31, 31))
        self.OSDSetBetaKey.setText("")
        self.OSDSetBetaKey.setMaxLength(1)
        self.OSDSetBetaKey.setObjectName("OSDSetBetaKey")
        self.prearmSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.prearmSetBetaLabel.setGeometry(QtCore.QRect(200, 180, 51, 21))
        self.prearmSetBetaLabel.setObjectName("prearmSetBetaLabel")
        self.OSDDisableSetBetaLabel = QtWidgets.QLabel(self.groupBoxBeta)
        self.OSDDisableSetBetaLabel.setGeometry(QtCore.QRect(140, 380, 111, 21))
        self.OSDDisableSetBetaLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OSDDisableSetBetaLabel.setObjectName("OSDDisableSetBetaLabel")

        _translate = QtCore.QCoreApplication.translate
        self.armSetBetaLabel.setText(_translate("MainWindow", "Arm"))
        self.beeperSetBetaLabel.setText(_translate("MainWindow", "Beeper"))
        self.angleSetBetaLabel.setText(_translate("MainWindow", "Angle"))
        self.modesSetBetaLabel.setText(_translate("MainWindow", "Modes/Features"))
        self.horizonSetBetaLabel.setText(_translate("MainWindow", "Horizon"))
        self.acroSetBetaLabel.setText(_translate("MainWindow", "Acro"))
        self.prearmSetBetaLabel.setText(_translate("MainWindow", "Prearm"))
        self.OSDDisableSetBetaLabel.setText(_translate("MainWindow", "OSD Disable SW"))
