from PyQt5 import QtCore, QtWidgets

class ControlSettingWidget(QtWidgets.QWidget):
    def __init__(self, page, parent=None):
        QtWidgets.QWidget.__init__(self, parent=parent)
        self.controlSetVerticalLay = QtWidgets.QVBoxLayout()
        self.controlSetVerticalLay.setObjectName("controlSetVerticalLay")
        self.controlsSetLabel = QtWidgets.QLabel(page)
        self.controlsSetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.controlsSetLabel.setObjectName("controlsSetLabel")
        self.controlSetVerticalLay.addWidget(self.controlsSetLabel)
        self.controlSetGrid = QtWidgets.QGridLayout()
        self.controlSetGrid.setObjectName("controlSetGrid")
        self.throttleSetDown = QtWidgets.QComboBox(page)
        self.throttleSetDown.setObjectName("throttleSetDown")
        self.controlSetGrid.addWidget(self.throttleSetDown, 0, 1, 1, 1)
        self.yawSetLabel = QtWidgets.QLabel(page)
        # self.yawSetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yawSetLabel.setObjectName("yawSetLabel")
        self.controlSetGrid.addWidget(self.yawSetLabel, 1, 0, 1, 1)
        self.yawSetAnticlockwise = QtWidgets.QComboBox(page)
        self.yawSetAnticlockwise.setObjectName("yawSetAnticlockwise")
        self.controlSetGrid.addWidget(self.yawSetAnticlockwise, 1, 1, 1, 1)
        self.rollSetLabel = QtWidgets.QLabel(page)
        # self.rollSetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rollSetLabel.setObjectName("rollSetLabel")
        self.controlSetGrid.addWidget(self.rollSetLabel, 2, 0, 1, 1)
        self.throttleSetLabel = QtWidgets.QLabel(page)
        # self.throttleSetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.throttleSetLabel.setObjectName("throttleSetLabel")
        self.controlSetGrid.addWidget(self.throttleSetLabel, 0, 0, 1, 1)
        self.pitchSetBack = QtWidgets.QComboBox(page)
        self.pitchSetBack.setObjectName("pitchSetBack")
        self.controlSetGrid.addWidget(self.pitchSetBack, 3, 1, 1, 1)
        self.pitchSetLabel = QtWidgets.QLabel(page)
        # self.pitchSetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pitchSetLabel.setObjectName("pitchSetLabel")
        self.controlSetGrid.addWidget(self.pitchSetLabel, 3, 0, 1, 1)
        self.rollSetLeft = QtWidgets.QComboBox(page)
        self.rollSetLeft.setObjectName("rollSetLeft")
        self.controlSetGrid.addWidget(self.rollSetLeft, 2, 1, 1, 1)
        self.throttleSetUp = QtWidgets.QComboBox(page)
        self.throttleSetUp.setObjectName("throttleSetUp")
        self.controlSetGrid.addWidget(self.throttleSetUp, 0, 2, 1, 1)
        self.yawSetClockwise = QtWidgets.QComboBox(page)
        self.yawSetClockwise.setObjectName("yawSetClockwise")
        self.controlSetGrid.addWidget(self.yawSetClockwise, 1, 2, 1, 1)
        self.rollSetRight = QtWidgets.QComboBox(page)
        self.rollSetRight.setObjectName("rollSetRight")
        self.controlSetGrid.addWidget(self.rollSetRight, 2, 2, 1, 1)
        self.pitchSetFront = QtWidgets.QComboBox(page)
        self.pitchSetFront.setObjectName("pitchSetFront")
        self.controlSetGrid.addWidget(self.pitchSetFront, 3, 2, 1, 1)
        self.controlSetGrid.setColumnStretch(0, 1)
        self.controlSetGrid.setColumnStretch(1, 1)
        self.controlSetGrid.setColumnStretch(2, 1)
        self.controlSetVerticalLay.addLayout(self.controlSetGrid)
        self.controlSetVerticalLay.setStretch(1, 1)
        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.controlsSetLabel.setText(_translate("MainWindow", "Controls"))
        self.yawSetLabel.setText(_translate("MainWindow", "Yaw"))
        self.rollSetLabel.setText(_translate("MainWindow", "Roll"))
        self.throttleSetLabel.setText(_translate("MainWindow", "Throttle"))
        self.pitchSetLabel.setText(_translate("MainWindow", "Pitch"))

        
    def getWidget(self):
        return self.controlSetVerticalLay