from PyQt5 import QtCore, QtWidgets

def initPage2(self, MainWindow):
    self.page_2 = QtWidgets.QWidget()
    self.page_2.setObjectName("page_2")
    self.controlsSetLabel = QtWidgets.QLabel(self.page_2)
    self.controlsSetLabel.setGeometry(QtCore.QRect(190, 120, 57, 15))
    self.controlsSetLabel.setObjectName("controlsSetLabel")
    self.layoutWidget = QtWidgets.QWidget(self.page_2)
    self.layoutWidget.setGeometry(QtCore.QRect(200, 60, 481, 31))
    self.layoutWidget.setObjectName("layoutWidget")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
    self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.typeBoxLabel = QtWidgets.QLabel(self.layoutWidget)
    self.typeBoxLabel.setObjectName("typeBoxLabel")
    self.horizontalLayout.addWidget(self.typeBoxLabel)
    self.typeDropDown = QtWidgets.QComboBox(self.layoutWidget)
    self.typeDropDown.setObjectName("typeDropDown")
    self.typeDropDown.addItem("")
    self.typeDropDown.addItem("")
    self.horizontalLayout.addWidget(self.typeDropDown)
    self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
    self.layoutWidget1.setGeometry(QtCore.QRect(260, 160, 64, 261))
    self.layoutWidget1.setObjectName("layoutWidget1")
    self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
    self.gridLayout.setContentsMargins(0, 0, 0, 0)
    self.gridLayout.setObjectName("gridLayout")
    self.throttleSetUp = QtWidgets.QLineEdit(self.layoutWidget1)
    self.throttleSetUp.setText("")
    self.throttleSetUp.setMaxLength(1)
    self.throttleSetUp.setObjectName("throttleSetUp")
    self.gridLayout.addWidget(self.throttleSetUp, 0, 0, 1, 1)
    self.throttleSetDown = QtWidgets.QLineEdit(self.layoutWidget1)
    self.throttleSetDown.setText("")
    self.throttleSetDown.setMaxLength(1)
    self.throttleSetDown.setObjectName("throttleSetDown")
    self.gridLayout.addWidget(self.throttleSetDown, 0, 1, 1, 1)
    self.yawSetClockwise = QtWidgets.QLineEdit(self.layoutWidget1)
    self.yawSetClockwise.setText("")
    self.yawSetClockwise.setMaxLength(1)
    self.yawSetClockwise.setObjectName("yawSetClockwise")
    self.gridLayout.addWidget(self.yawSetClockwise, 1, 0, 1, 1)
    self.yawSetAnticlockwise = QtWidgets.QLineEdit(self.layoutWidget1)
    self.yawSetAnticlockwise.setText("")
    self.yawSetAnticlockwise.setMaxLength(1)
    self.yawSetAnticlockwise.setObjectName("yawSetAnticlockwise")
    self.gridLayout.addWidget(self.yawSetAnticlockwise, 1, 1, 1, 1)
    self.rollSetLeft = QtWidgets.QLineEdit(self.layoutWidget1)
    self.rollSetLeft.setText("")
    self.rollSetLeft.setMaxLength(1)
    self.rollSetLeft.setObjectName("rollSetLeft")
    self.gridLayout.addWidget(self.rollSetLeft, 2, 0, 1, 1)
    self.rollSetRight = QtWidgets.QLineEdit(self.layoutWidget1)
    self.rollSetRight.setText("")
    self.rollSetRight.setMaxLength(1)
    self.rollSetRight.setObjectName("rollSetRight")
    self.gridLayout.addWidget(self.rollSetRight, 2, 1, 1, 1)
    self.pitchSetFront = QtWidgets.QLineEdit(self.layoutWidget1)
    self.pitchSetFront.setText("")
    self.pitchSetFront.setMaxLength(1)
    self.pitchSetFront.setObjectName("pitchSetFront")
    self.gridLayout.addWidget(self.pitchSetFront, 3, 0, 1, 1)
    self.pitchSetBack = QtWidgets.QLineEdit(self.layoutWidget1)
    self.pitchSetBack.setText("")
    self.pitchSetBack.setMaxLength(1)
    self.pitchSetBack.setObjectName("pitchSetBack")
    self.gridLayout.addWidget(self.pitchSetBack, 3, 1, 1, 1)
    self.layoutWidget2 = QtWidgets.QWidget(self.page_2)
    self.layoutWidget2.setGeometry(QtCore.QRect(110, 170, 61, 241))
    self.layoutWidget2.setObjectName("layoutWidget2")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
    self.verticalLayout.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout.setObjectName("verticalLayout")
    self.throttleSetLabel = QtWidgets.QLabel(self.layoutWidget2)
    self.throttleSetLabel.setObjectName("throttleSetLabel")
    self.verticalLayout.addWidget(self.throttleSetLabel)
    self.yawSetLabel = QtWidgets.QLabel(self.layoutWidget2)
    self.yawSetLabel.setObjectName("yawSetLabel")
    self.verticalLayout.addWidget(self.yawSetLabel)
    self.rollSetLabel = QtWidgets.QLabel(self.layoutWidget2)
    self.rollSetLabel.setObjectName("rollSetLabel")
    self.verticalLayout.addWidget(self.rollSetLabel)
    self.pitchSetLabel = QtWidgets.QLabel(self.layoutWidget2)
    self.pitchSetLabel.setObjectName("pitchSetLabel")
    self.verticalLayout.addWidget(self.pitchSetLabel)
    self.selectButton = QtWidgets.QPushButton(self.page_2)
    self.selectButton.setGeometry(QtCore.QRect(700, 60, 80, 31))
    self.selectButton.setObjectName("selectButton")
    self.confirmSetButton = QtWidgets.QPushButton(self.page_2)
    self.confirmSetButton.setGeometry(QtCore.QRect(440, 460, 161, 31))
    self.confirmSetButton.setObjectName("confirmSetButton")
    self.stackedWidget.addWidget(self.page_2)

    _translate = QtCore.QCoreApplication.translate
    self.controlsSetLabel.setText(_translate("MainWindow", "Controls"))
    self.typeBoxLabel.setText(_translate("MainWindow", "Please select drone system"))
    self.typeDropDown.setItemText(0, _translate("MainWindow", "Betaflight System Based Drones"))
    self.typeDropDown.setItemText(1, _translate("MainWindow", "Ardupilot System Based Drones"))
    self.throttleSetLabel.setText(_translate("MainWindow", "Throttle"))
    self.yawSetLabel.setText(_translate("MainWindow", "Yaw"))
    self.rollSetLabel.setText(_translate("MainWindow", "Roll"))
    self.pitchSetLabel.setText(_translate("MainWindow", "Pitch"))
    self.selectButton.setText(_translate("MainWindow", "Select"))
    self.confirmSetButton.setText(_translate("MainWindow", "Confirm Your Settings"))

    self.selectButton.clicked.connect(self.changeInterfaceBasedOnModel)
