# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap

HOMEPAGE = 0
CONTROLPAGE = 1
SWARMPAGE = 2
SETTINGPAGE = 3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 642)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1031, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setObjectName("page")
        self.displayFrame = QtWidgets.QLabel(self.page)
        self.displayFrame.setGeometry(QtCore.QRect(70, 10, 451, 451))
        self.displayFrame.setStyleSheet("")
        self.displayFrame.setText("")
        self.displayFrame.setObjectName("displayFrame")
        self.Stop = QtWidgets.QPushButton(self.page)
        self.Stop.setGeometry(QtCore.QRect(170, 480, 80, 23))
        self.Stop.setObjectName("Stop")
        self.Start = QtWidgets.QPushButton(self.page)
        self.Start.setGeometry(QtCore.QRect(330, 480, 80, 23))
        self.Start.setObjectName("Start")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(530, 0, 451, 501))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("border:0")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.currentMode = QtWidgets.QLineEdit(self.groupBox)
        self.currentMode.setGeometry(QtCore.QRect(310, 270, 31, 31))
        self.currentMode.setText("")
        self.currentMode.setMaxLength(1)
        self.currentMode.setObjectName("currentMode")
        self.prearmLabel = QtWidgets.QLabel(self.groupBox)
        self.prearmLabel.setGeometry(QtCore.QRect(200, 180, 51, 21))
        self.prearmLabel.setObjectName("prearmLabel")
        self.modesLabel = QtWidgets.QLabel(self.groupBox)
        self.modesLabel.setGeometry(QtCore.QRect(210, 100, 121, 21))
        self.modesLabel.setObjectName("modesLabel")
        self.beeperLabel = QtWidgets.QLabel(self.groupBox)
        self.beeperLabel.setGeometry(QtCore.QRect(200, 330, 51, 21))
        self.beeperLabel.setObjectName("beeperLabel")
        self.flightmodeKey = QtWidgets.QLineEdit(self.groupBox)
        self.flightmodeKey.setGeometry(QtCore.QRect(260, 270, 31, 31))
        self.flightmodeKey.setText("")
        self.flightmodeKey.setMaxLength(1)
        self.flightmodeKey.setObjectName("flightmodeKey")
        self.armKey = QtWidgets.QLineEdit(self.groupBox)
        self.armKey.setGeometry(QtCore.QRect(260, 220, 31, 31))
        self.armKey.setText("")
        self.armKey.setMaxLength(1)
        self.armKey.setObjectName("armKey")
        self.beeperKey = QtWidgets.QLineEdit(self.groupBox)
        self.beeperKey.setGeometry(QtCore.QRect(260, 320, 31, 31))
        self.beeperKey.setText("")
        self.beeperKey.setMaxLength(1)
        self.beeperKey.setObjectName("beeperKey")
        self.horizonLabel = QtWidgets.QLabel(self.groupBox)
        self.horizonLabel.setGeometry(QtCore.QRect(150, 280, 61, 21))
        self.horizonLabel.setObjectName("horizonLabel")
        self.acroLabel = QtWidgets.QLabel(self.groupBox)
        self.acroLabel.setGeometry(QtCore.QRect(220, 280, 31, 21))
        self.acroLabel.setObjectName("acroLabel")
        self.OSDKey = QtWidgets.QLineEdit(self.groupBox)
        self.OSDKey.setGeometry(QtCore.QRect(260, 370, 31, 31))
        self.OSDKey.setText("")
        self.OSDKey.setMaxLength(1)
        self.OSDKey.setObjectName("OSDKey")
        self.OSDDisableLabel = QtWidgets.QLabel(self.groupBox)
        self.OSDDisableLabel.setGeometry(QtCore.QRect(140, 380, 111, 21))
        self.OSDDisableLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.OSDDisableLabel.setObjectName("OSDDisableLabel")
        self.armLabel = QtWidgets.QLabel(self.groupBox)
        self.armLabel.setGeometry(QtCore.QRect(210, 230, 31, 21))
        self.armLabel.setObjectName("armLabel")
        self.angleLabel = QtWidgets.QLabel(self.groupBox)
        self.angleLabel.setGeometry(QtCore.QRect(90, 280, 41, 21))
        self.angleLabel.setObjectName("angleLabel")
        self.prearmKey = QtWidgets.QLineEdit(self.groupBox)
        self.prearmKey.setGeometry(QtCore.QRect(260, 170, 31, 31))
        self.prearmKey.setText("")
        self.prearmKey.setMaxLength(1)
        self.prearmKey.setObjectName("prearmKey")
        self.stackedWidget.addWidget(self.page)
        # self.page_3 = QtWidgets.QWidget()
        # self.page_3.setObjectName("page_3")
        # self.stackedWidget.addWidget(self.page_3)
        # self.page_4 = QtWidgets.QWidget()
        # self.page_4.setObjectName("page_4")
        # self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_File.menuAction())


        self.flightDataLabel = QtWidgets.QLabel()
        self.flightDataLabel.setGeometry(QtCore.QRect(720, 240, 31, 21))
        self.flightDataLabel.setObjectName("flightDataLabel")
        self.createActions(MainWindow)
        self.toolBar.addWidget(self.flightDataLabel)


        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.prearmLabel.setText(_translate("MainWindow", "Prearm"))
        self.modesLabel.setText(_translate("MainWindow", "Modes/Features"))
        self.beeperLabel.setText(_translate("MainWindow", "Beeper"))
        self.horizonLabel.setText(_translate("MainWindow", "Horizon"))
        self.acroLabel.setText(_translate("MainWindow", "Acro"))
        self.OSDDisableLabel.setText(_translate("MainWindow", "OSD Disable SW"))
        self.armLabel.setText(_translate("MainWindow", "Arm"))
        self.angleLabel.setText(_translate("MainWindow", "Angle"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        
        self.flightDataLabel.setText(_translate("MainWindow", "Flight Data:"))

        

    #CREATE ACTIONS FOR TOOL BAR
    def createActions(self, mainWindowBase):
        self.homeAction = QtWidgets.QAction(mainWindowBase)
        self.homeAction.setText("&Home")
        self.homeAction.setIcon(QIcon(QPixmap("./icons/house-icon.webp")))
        self.toolBar.addAction(self.homeAction)
        self.homeAction.triggered.connect(lambda: self.toPage(HOMEPAGE))

        self.controlAction = QtWidgets.QAction(mainWindowBase)
        self.controlAction.setText("&Drone Controls")
        self.controlAction.setIcon(QIcon(QPixmap("./icons/control-panel-icon.webp")))
        self.toolBar.addAction(self.controlAction)
        self.controlAction.triggered.connect(lambda: self.toPage(CONTROLPAGE))

        self.swarmAction = QtWidgets.QAction(mainWindowBase)
        self.swarmAction.setText("&Swarming")
        self.swarmAction.setIcon(QIcon(QPixmap("./icons/air-drone-icon.png")))
        self.toolBar.addAction(self.swarmAction)
        self.swarmAction.triggered.connect(lambda: self.toPage(SWARMPAGE))


        self.settingAction = QtWidgets.QAction(mainWindowBase)
        self.settingAction.setText("&Setting")
        self.settingAction.setIcon(QIcon(QPixmap("./icons/setting-line-icon.webp")))
        self.toolBar.addAction(self.settingAction)
        self.settingAction.triggered.connect(lambda: self.toPage(SETTINGPAGE))


        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setStyleSheet("QToolBar{spacing:30px;}")
    

    #REDIRECT PAGE AFTER CLICKING TOOLBAR ICONS
    def toPage(self, pageNumber):

        self.stackedWidget.setCurrentIndex(pageNumber)