# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ControlSettingWidget import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 626)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.centralWidgetGrid = QtWidgets.QGridLayout(self.centralwidget)
        self.centralWidgetGrid.setObjectName("centralWidgetGrid")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setObjectName("page")
        self.page1HorizontalLay = QtWidgets.QHBoxLayout(self.page)
        self.page1HorizontalLay.setObjectName("page1HorizontalLay")
        self.page1CamVerticalLay = QtWidgets.QVBoxLayout()
        self.page1CamVerticalLay.setObjectName("page1CamVerticalLay")
        self.displayFrame = QtWidgets.QLabel(self.page)
        self.displayFrame.setStyleSheet("")
        self.displayFrame.setText("")
        self.displayFrame.setObjectName("displayFrame")
        self.displayFrame.setMinimumSize(1, 1)
        self.page1CamVerticalLay.addWidget(self.displayFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.page1CamVerticalLay.addItem(spacerItem)
        self.page1ButHorizontalLay = QtWidgets.QHBoxLayout()
        self.page1ButHorizontalLay.setObjectName("page1ButHorizontalLay")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page1ButHorizontalLay.addItem(spacerItem1)
        self.Stop = QtWidgets.QPushButton(self.page)
        self.Stop.setObjectName("Stop")
        self.page1ButHorizontalLay.addWidget(self.Stop)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page1ButHorizontalLay.addItem(spacerItem2)
        self.Start = QtWidgets.QPushButton(self.page)
        self.Start.setObjectName("Start")
        self.page1ButHorizontalLay.addWidget(self.Start)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page1ButHorizontalLay.addItem(spacerItem3)
        self.page1ButHorizontalLay.setStretch(1, 2)
        self.page1ButHorizontalLay.setStretch(2, 1)
        self.page1ButHorizontalLay.setStretch(3, 2)
        self.page1CamVerticalLay.addLayout(self.page1ButHorizontalLay)
        self.page1CamVerticalLay.setStretch(0, 1)
        self.page1HorizontalLay.addLayout(self.page1CamVerticalLay)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.page1HorizontalLay.addItem(spacerItem4)
        self.homeSettingVerticalLay = QtWidgets.QVBoxLayout()
        self.homeSettingVerticalLay.setObjectName("homeSettingVerticalLay")
        
        self.controlHomeSetting = ControlSettingWidget(self.page).getWidget()
        self.homeSettingVerticalLay.addLayout(self.controlHomeSetting)
        self.page1HorizontalLay.addLayout(self.homeSettingVerticalLay)
        self.page1HorizontalLay.setStretch(0, 1)
        self.page1HorizontalLay.setStretch(2, 1)
        self.stackedWidget.addWidget(self.page)
        # self.page_2 = QtWidgets.QWidget()
        # self.page_2.setObjectName("page_2")
        # self.stackedWidget.addWidget(self.page_2)
        # self.page_3 = QtWidgets.QWidget()
        # self.page_3.setObjectName("page_3")
        # self.stackedWidget.addWidget(self.page_3)
        # self.page_4 = QtWidgets.QWidget()
        # self.page_4.setObjectName("page_4")
        # self.stackedWidget.addWidget(self.page_4)
        self.centralWidgetGrid.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 20))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
